# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [63]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [64]:
!pip show numpy

Name: numpy
Version: 1.25.2
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: /usr/local/lib/python3.10/dist-packages
Requires: 
Required-by: albumentations, altair, arviz, astropy, autograd, blis, bokeh, bqplot, chex, cmdstanpy, contourpy, cudf-cu12, cufflinks, cupy-cuda12x, cvxpy, datascience, db-dtypes, dopamine_rl, ecos, flax, folium, geemap, gensim, gym, h5py, holoviews, hyperopt, ibis-framework, imageio, imbalanced-learn, imgaug, jax, jaxlib, librosa, lightgbm, matplotlib, matplotlib-venn, missingno, mizani, ml-dtypes, mlxtend, moviepy, music21, nibabel, numba, numexpr, opencv-contrib-python, opencv-python, opencv-python-headless, opt-einsum, optax, orbax-checkpoint, osqp, pandas, pandas-gbq, pandas-stubs, patsy, plotnine, prophet, pyarrow, pycocotools, pyerfa, pymc, pytensor, python-louvain, PyWavelets, qdldl, qudida, rmm-cu12, scikit-image, scikit-learn, sc

#### 3. Create a null vector of size 10

In [66]:
nv = np.zeros(10)
print(nv)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [67]:
print(nv.size)

10


#### 5.  How to get the documentation of the numpy add function from the command line?

In [68]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [69]:
null_v = np.zeros(10)
null_v[4] = 1
print(null_v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [71]:
avec = np.arange(10, 49)
print(avec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last)

In [72]:
avec = avec[::-1]
print(avec)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [73]:
mat1 = np.arange(0, 9).reshape(3, 3)
print(mat1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [74]:
elem = np.array([1,2,0,0,4,0])
print(np.nonzero(elem))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [75]:
ide = np.identity(3)
print(ide)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [76]:
arr = np.random.rand(3, 3, 3)
print(arr)

[[[0.30221598 0.85277332 0.78868247]
  [0.45125593 0.04231232 0.91634344]
  [0.71573248 0.6460192  0.3768411 ]]

 [[0.51003937 0.63531059 0.04392815]
  [0.98817551 0.64250518 0.79982137]
  [0.73643363 0.45373693 0.1093208 ]]

 [[0.68073792 0.44157572 0.10435819]
  [0.6445239  0.27871227 0.8687612 ]
  [0.37943249 0.7949971  0.20741346]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [77]:
arr2 = np.random.rand(10,10)
print(arr2)
print(np.min(arr2))
print(np.max(arr2))

[[0.1320277  0.52095857 0.04685133 0.19558388 0.12553607 0.50549882
  0.21224291 0.74370411 0.79097796 0.73186133]
 [0.73738095 0.47758492 0.08489478 0.26321234 0.16481779 0.45013811
  0.61748777 0.08464431 0.42615046 0.93422156]
 [0.52513921 0.54957098 0.79669103 0.28600422 0.68526729 0.50610428
  0.56403837 0.94750064 0.34249098 0.02821588]
 [0.68207968 0.12006081 0.47429186 0.0338859  0.18245529 0.1916237
  0.8274376  0.64228758 0.83654537 0.15512556]
 [0.30502067 0.43289531 0.29252822 0.71889837 0.81893766 0.14992704
  0.40870078 0.33242713 0.83617031 0.86747303]
 [0.15888144 0.50641373 0.07568223 0.39961414 0.87308843 0.22790661
  0.07120733 0.30232926 0.84439731 0.79196811]
 [0.82147062 0.03048532 0.75683858 0.82933865 0.54357868 0.74686048
  0.39922454 0.83165401 0.80808808 0.46645122]
 [0.42880909 0.81448491 0.6570415  0.37760948 0.454303   0.45097131
  0.13209534 0.45199069 0.87166703 0.63182503]
 [0.75883669 0.70180127 0.54523909 0.20499551 0.31158231 0.73282624
  0.70839502 

#### 14. Create a random vector of size 30 and find the mean value

In [78]:
rvec = np.random.rand(30)
print(rvec)
print(np.mean(rvec))

[0.45630786 0.59518985 0.91768827 0.7548642  0.43567996 0.29465867
 0.49327791 0.83565213 0.26730213 0.99893582 0.89988592 0.92948302
 0.92277838 0.70772901 0.93337755 0.09353211 0.73848504 0.5071659
 0.76927626 0.08200676 0.27596849 0.38074178 0.90841371 0.62898048
 0.26184863 0.46859096 0.1897706  0.03200833 0.73053255 0.94326237]
0.5817798213596129


#### 15. Create a 2d array with 1 on the border and 0 inside

In [79]:
arr2d = np.zeros((2,2))
arr2d = np.pad(arr2d, pad_width = 1,mode='constant', constant_values = 1)
print(arr2d)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [80]:
myarr = np.random.randint(1,100, size=(3,4))
myarr = np.pad(myarr,pad_width = 1, mode = 'constant', constant_values = 1)
print(myarr)

[[ 1  1  1  1  1  1]
 [ 1 45 79  1 25  1]
 [ 1 87 14 19 39  1]
 [ 1  6 54 30 69  1]
 [ 1  1  1  1  1  1]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

* `0 * np.nan` -> nan : multilpying 0 by np.nan results in nan(not a number)
* `np.nan == np.nan` -> false : any comparison with nan gives 'false'
* `np.inf > np.nan` -> false : any comparison with nan gives 'false'
* `np.nan - np.nan` -> np.nan : any airthmetic operations with np.nan gives nan
* `np.nan in set([np.nan])` -> True : Checking if np.nan is in a set containing np.nan, returns True
* `0.3 == 3 * 0.1` -> True

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [82]:
mat = np.arange(0, 25).reshape(5, 5)
val = np.array([1, 2, 3, 4])

res = np.diag(val, k=-1)
print(res)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [83]:
matr = np.ones((3, 3))
matr = np.zeros((5, 5))
matr[1::2, ::2] = 1
matr[::2, 1::2] = 1
print(matr)

[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]



20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [84]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)
