There are 5 general mechanisms for creating arrays:

    Conversion from other Python structures (e.g., lists, tuples)
    Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)
    Reading arrays from disk, either from standard or custom formats
    Creating arrays from raw bytes through the use of strings or buffers
    Use of special library functions (e.g., random)


In [2]:
import numpy as np

In [3]:
# Create a NumPy array of integers with default data type

myarr = np.array([3,6,37,7])

In [4]:
myarr

array([ 3,  6, 37,  7])

In [5]:
# Create a NumPy array of integers with specified data type int8

myarr = np.array([3,6,37,7], np.int8)
myarr

array([ 3,  6, 37,  7], dtype=int8)

In [6]:
# Access the element at the second row and third column of the array

arr1 = np.array([[1,2,3],
                 [4,5,6]])

arr1[1,2]

6

In [7]:
# Print the shape of the array

arr1.shape

(2, 3)

In [8]:
arr1.dtype

dtype('int32')

In [9]:
# Update a specific element in the array

arr1[1,1] = 55

In [10]:
arr1

array([[ 1,  2,  3],
       [ 4, 55,  6]])

# **Conversion from other Python structures (e.g., lists, tuples)**


In [12]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9],[10,11,12]])
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
arr2.size

12

In [14]:
arr2.dtype

dtype('int32')

In [15]:
arr2.shape

(4, 3)

In [16]:
# Create a NumPy array from a set

np.array({34, 22, 39})

array({34, 22, 39}, dtype=object)

# **Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)**

In [18]:
# Create a 2x5 NumPy array initialized with zeros

zeroarr = np.zeros((2, 5))

In [19]:
zeroarr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
# Create a NumPy array with values ranging from 0 to 14

rng = np.arange(15)

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
# Create a NumPy array with evenly spaced values from 1 to 4, with 4 elements

lspace = np.linspace(1, 4, 4)
lspace

array([1., 2., 3., 4.])

In [23]:
lspace

array([1., 2., 3., 4.])

In [24]:
# Create a NumPy array with evenly spaced values from 1 to 10, with 5 elements

lspace = np.linspace(1, 10, 5)
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
# Create an uninitialized NumPy array of shape (3, 4)

emp = np.empty((3,4))
emp

array([[ 7.63755155e-159,  7.91237176e-141, -3.17435806e+116,
         8.44560328e-072],
       [ 4.81892021e-154,  3.67582555e-304,  2.29884140e-287,
         6.81399892e-145],
       [ 8.70548195e-261,  5.37910252e-299,  2.06285343e+149,
         3.28703410e+231]])

In [26]:
# Create a 5x5 identity matrix using NumPy

ide = np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
# Create a NumPy array with values ranging from 0 to 68

arr4 = np.arange(69)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68])

In [28]:
# Reshape the array into a 3x23 array

arr4.reshape(3,23)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
        39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
        62, 63, 64, 65, 66, 67, 68]])

In [29]:
# Flatten the array into a 1-dimensional array

arr4 = arr4.ravel()
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68])

In [30]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [31]:
ar = np.array(x)

In [32]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
# Compute the sum along axis 0 (column-wise elements) of the array ar

ar.sum(axis=0)

array([12, 15, 18])

In [34]:
# Compute the sum along axis 1 of the array ar

ar.sum(axis=1)

array([ 6, 15, 24])

In [35]:
# Transpose the array ar

ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
# Create a 2x3 NumPy array and iterate through its flattened elements

arr5 = np.array([[1,2,30], [11, 5, 10]])
arr5

for item in arr5.flat:
    print(item)

1
2
30
11
5
10


In [37]:
# Get the number of dimensions of the array arr5

arr5.ndim

2

In [38]:
# Get the number of elements in the array arr5

arr5.size

6

In [39]:
# Get the number of bytes used by the array ar

arr5.nbytes

24

In [40]:
# Get the index of the maximum value in the array arr6

arr6 = np.array([1, 57, 371, 76,-1, 32])
arr6.argmax()

2

In [41]:
# Get the index of the minimum value in the array arr6

arr6.argmin()

4

In [42]:
# Get the indices that would sort the array arr6

arr6.argsort()

array([4, 0, 5, 1, 3, 2], dtype=int64)

In [43]:
# Get the index of the minimum value in the flattened array arr7

arr7 = np.array([[3, 4, 7],
       [21, 1, 8],
       [4, 12, 9]])
arr7.argmin()

4

In [44]:
# Get the index of the maximum value in the flattened array arr7
arr7.argmax()

3

In [45]:
# Get the indices that would sort each row of the array arr7

arr7.argsort()

array([[0, 1, 2],
       [1, 2, 0],
       [0, 2, 1]], dtype=int64)

In [46]:
# Get the indices of the maximum values along axis 0 of the array arr7

arr7.argmax(axis=0)

array([1, 2, 2], dtype=int64)

In [47]:
arr7.argmax(axis=1)

array([2, 0, 1], dtype=int64)

In [48]:
arr7.ravel()

array([ 3,  4,  7, 21,  1,  8,  4, 12,  9])

In [49]:
arr7.reshape((9,1))

array([[ 3],
       [ 4],
       [ 7],
       [21],
       [ 1],
       [ 8],
       [ 4],
       [12],
       [ 9]])

# Matrix Operations

In [51]:
ar1 = np.array([[1, 4, 7],
                [2, 5, 8],
                [3, 6, 9]])

In [52]:
ar2 = np.array([[1, 2, 3],
                [4, 5, 6],
                [0, 1, 2]])

In [53]:
ar3 = ar1 + ar2
print(ar3)

[[ 2  6 10]
 [ 6 10 14]
 [ 3  7 11]]


In [54]:
ar4 = np.array([[1, 4, 9],
                [121, 25, 0],
                [225, 36, 49]])

In [55]:
np.sqrt(ar4)

array([[ 1.,  2.,  3.],
       [11.,  5.,  0.],
       [15.,  6.,  7.]])

In [56]:
ar4.sum()

470

In [57]:
ar4.max()

225

In [58]:
ar4.min()

0

In [59]:
# Get the indices of elements in ar4 that are greater than 50

np.where(ar4 > 50)

(array([1, 2], dtype=int64), array([0, 0], dtype=int64))

In [60]:
# Count the number of non-zero elements in the array ar4

np.count_nonzero(ar4)

8

In [120]:
# Get the indices of non-zero elements in ar4

np.nonzero(ar4)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [122]:
ar5 = np.array([[1, 4, 9],
                [121, 25, 0],
                [225, 36, 49]])

array([[  2,   5,  10],
       [122,  26,   1],
       [226,  37,  50]])

In [ ]:
# Add 1 to each element of the array ar5

ar5+1

In [124]:
# Subtract 1 from each element of the array ar5

ar5-1

array([[  0,   3,   8],
       [120,  24,  -1],
       [224,  35,  48]])

In [128]:
# Multiply each element of the array ar5 by 2

ar5*2

array([[  2,   8,  18],
       [242,  50,   0],
       [450,  72,  98]])

In [130]:
# Square each element of the array ar5

ar5**2

array([[    1,    16,    81],
       [14641,   625,     0],
       [50625,  1296,  2401]])

In [132]:
# Transpose the array ar5

ar5.T

array([[  1, 121, 225],
       [  4,  25,  36],
       [  9,   0,  49]])